services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: meilisearch-manager-next
    hostname: meilisearch-manager-next
    entrypoint: /bin/bash
    working_dir: /workspace
    volumes:
      - '.:/workspace'
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meilisearch-manager-next.rule=Host(`meilisearch-manager-next.localhost`)"
      - "traefik.http.services.meilisearch-manager-next.loadbalancer.server.port=${NUXT_APP_PORT:-3000}"
    networks:
      - proxy
      - web

  meilisearch:
    image: 'getmeili/meilisearch:latest'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    environment:
      MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-true}'
      MEILI_MASTER_KEY: '${MEILISEARCH_MASTER_KEY:-masterKey}'
      MEILI_ENV: development
    volumes:
      - 'meilisearch-data:/meili_data'
    networks:
      - web
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--spider'
        - 'http://127.0.0.1:7700/health'
      retries: 3
      timeout: 5s

volumes:
  meilisearch-data:

networks:
  web:
  proxy: # setup in separate compose file
    name: "traefik_proxy"
    external: true
