services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: meilisearch-manager
    hostname: meilisearch-manager
    entrypoint: /bin/bash
    working_dir: /workspace
    group_add:
      - '${DOCKER_GID:-1001}'
    volumes:
      - '${LOCAL_WORKSPACE_FOLDER:-.}:/workspace'
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meilisearch-manager.rule=Host(`meilisearch-manager.localhost`)"
      - "traefik.http.services.meilisearch-manager.loadbalancer.server.port=${NUXT_APP_PORT:-3000}"
    networks:
      - proxy
      - web

  meilisearch:
    image: 'getmeili/meilisearch:${MEILISEARCH_VERSION:-latest}'
    # command:
    #   - /bin/meilisearch
    #   - --upgrade-db # v1.51 and up
    #   - --experimental-dumpless-upgrade # v1.50 and below
    restart: unless-stopped
    stop_grace_period: 1m
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    environment:
      MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-true}'
      MEILI_MASTER_KEY: '${MEILISEARCH_MASTER_KEY:-masterKey}'
      MEILI_ENV: development
    volumes:
      - 'meilisearch-data:/meili_data'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meilisearch-manager-instance.rule=Host(`instance.meilisearch-manager.localhost`)"
      - "traefik.http.services.meilisearch-manager-instance.loadbalancer.server.port=7700"
    networks:
      - proxy
      - web
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--spider'
        - 'http://127.0.0.1:7700/health'
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s

volumes:
  meilisearch-data:

networks:
  web:
  proxy: # setup in separate compose file
    name: "traefik_proxy"
    external: true
