<script setup lang="ts">
import { useKeys } from '@/composables/meilisearch/useKeys'
import { useIndexes } from '@/composables/meilisearch/useIndexes'
import type { KeyCreation } from 'meilisearch'
import { useToast } from 'primevue'
import { CircleQuestionMark, Info } from '@lucide/vue'
import { keyActions } from '@/utils/data'

const drawerOpen = defineModel<boolean>({ default: false })

const emit = defineEmits(['hide', 'key-created'])

const toast = useToast()
const { indexes, isFetching: isFetchingIndexes, fetchAllIndexes } = useIndexes()
const { isLoading, createKey } = useKeys()

const indexOptions = computed(() => {
    return (allIndexes.value) ? ['*'] : indexes.value.map((index) => index.uid)
})
const actionsOptions = computed(() => {
    return (allActions.value) ? ['*'] : keyActions
})

const defaultDate = new Date()
defaultDate.setDate(defaultDate.getDate() + 1)
defaultDate.setHours(0, 0, 0, 0)

const emptyKey = {
    uid: undefined,
    name: undefined,
    description: undefined,
    actions: [],
    indexes: [],
    expiresAt: null,
}
const newKey = ref<KeyCreation>(structuredClone(toRaw(emptyKey)))
const allIndexes = ref(false)
const allActions = ref(false)
function submitNewKey() {
    createKey(newKey.value).then(() => {
        toast.add({
            severity: 'success',
            summary: 'API Key Created',
            detail: `The API key: "${newKey.value.name}" was successfully created`,
            life: 3000,
        })
        drawerOpen.value = false
        emit('key-created')
    }).catch(() => {
        // TODO
    })
}

function reset() {
    newKey.value = structuredClone(toRaw(emptyKey))
    allIndexes.value = false
    allActions.value = false
}

function handleHideDrawer() {
    reset()
    emit('hide')
}

watch(newKey, (newVal) => {
    if (newVal.uid === '') {
        delete newKey.value.uid
    }
    if (newVal.name === '') {
        delete newKey.value.name
    }
    if (newVal.description === '') {
        delete newKey.value.description
    }
}, { deep: true })
watch(allIndexes, (newVal) => {
    newKey.value.indexes = (newVal) ? ['*'] : []
})
watch(allActions, (newVal) => {
    newKey.value.actions = (newVal) ? ['*'] : []
})
</script>

<template>
    <Drawer
        v-model:visible="drawerOpen"
        header="New API Key"
        class="w-full sm:w-[40rem]"
        position="right"
        @show="fetchAllIndexes"
        @hide="handleHideDrawer"
    >
        <form
            id="create-key-form"
            class="space-y-6 sm:space-y-8"
            @submit.prevent="submitNewKey"
        >
            <div class="flex flex-col gap-2">
                <label for="new-key-uid">UID</label>
                <InputText
                    id="new-key-uid"
                    v-model="newKey.uid"
                    placeholder="optional - set UID"
                    type="text"
                    fluid
                />
                <Message severity="info">
                    <template #icon>
                        <Info />
                    </template>
                    <div class="text-sm">
                        A <a
                            href="https://www.sohamkamani.com/uuid-versions-explained/"
                            target="_blank"
                            class="text-inherit underline"
                        >uuid v4</a>
                        to identify the API key. If not specified, it is generated by Meilisearch
                    </div>
                </Message>
            </div>
            <div class="flex flex-col gap-2">
                <label for="new-key-name">Name</label>
                <InputText
                    id="new-key-name"
                    v-model="newKey.name"
                    placeholder="name your key"
                    type="text"
                    autofocus
                    fluid
                />
            </div>
            <div class="flex flex-col gap-2">
                <label for="new-key-desc">Description</label>
                <Textarea
                    id="new-key-desc"
                    v-model="newKey.description"
                    placeholder="optional - set description"
                    rows="2"
                    autoResize
                    fluid
                />
            </div>
            <div class="flex flex-col gap-2">
                <!-- TODO: required validation -->
                <label for="new-key-indexes">Indexes</label>
                <MultiSelect
                    v-model="newKey.indexes"
                    pt:label:class="flex flex-wrap"
                    :options="indexOptions"
                    :display="allIndexes ? 'comma' : 'chip'"
                    placeholder="select permitted indexes"
                    inputId="new-key-indexes"
                    :loading="isFetchingIndexes"
                    :showToggleAll="false"
                    :disabled="allIndexes"
                    :showClear="!allIndexes"
                    filter
                    fluid
                />
                <div class="flex items-center gap-2">
                    <Checkbox
                        v-model="allIndexes"
                        inputId="new-key-all-indexes"
                        binary
                    />
                    <label for="new-key-all-indexes">All indexes</label>
                </div>
            </div>
            <div class="flex flex-col gap-2">
                <!-- TODO: required validation -->
                <label
                    for="new-key-actions"
                    class="flex items-center gap-2"
                >
                    <span>Actions</span>
                    <a
                        href="https://www.meilisearch.com/docs/reference/api/keys/create-api-key#body-actions"
                        target="_blank"
                        class="text-inherit underline"
                    >
                        <CircleQuestionMark />
                    </a>
                </label>
                <MultiSelect
                    v-model="newKey.actions"
                    pt:label:class="flex flex-wrap"
                    :options="actionsOptions"
                    :display="allActions ? 'comma' : 'chip'"
                    placeholder="select permitted actions"
                    inputId="new-key-actions"
                    :showToggleAll="false"
                    :disabled="allActions"
                    :showClear="!allActions"
                    filter
                    fluid
                />
                <div class="flex items-center gap-2">
                    <Checkbox
                        v-model="allActions"
                        inputId="new-key-all-actions"
                        binary
                    />
                    <label for="new-key-all-actions">All actions</label>
                </div>
            </div>
            <div class="flex flex-col gap-2">
                <label for="new-key-expires">Expires At</label>
                <DatePicker
                    id="new-key-expires"
                    v-model="newKey.expiresAt"
                    :defaultValue="defaultDate"
                    :minDate="new Date()"
                    placeholder="optional - select date & time"
                    hourFormat="12"
                    showTime
                    showButtonBar
                    fluid
                    @clear-click="newKey.expiresAt = null"
                />
            </div>
        </form>
        <template #footer>
            <Button
                type="submit"
                form="create-key-form"
                label="Submit"
                :loading="isLoading"
            />
        </template>
    </Drawer>
</template>
